DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    firstname TEXT NOT NULL,
    lastname TEXT NOT NULL
);

CREATE TABLE classes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    class TEXT NOT NULL,
    period1 INTEGER NOT NULL,
    period2 INTEGER NOT NULL,
    period3 INTEGER NOT NULL,
    period4 INTEGER NOT NULL,
    period5 INTEGER NOT NULL,
    period6 INTEGER NOT NULL,
    period7 INTEGER NOT NULL,
    period8 INTEGER NOT NULL
);